### ISSUE TITLE
TLS issues with go getting this package.

### ISSUE THREAD

**Issue by shurcooL** [azul3d/semver#15] opened 2015-09-21 19:07 UTC
See https://travis-ci.org/shurcooL/Go-Package-Store/builds/81445564:

```
get "azul3d.org/semver.v2": found meta tag main.metaImport{Prefix:"azul3d.org/semver.v2", VCS:"git", RepoRoot:"https://azul3d.org/semver.v2"} at https://azul3d.org/semver.v2?go-get=1
azul3d.org/semver.v2 (download)
# cd .; git clone https://azul3d.org/semver.v2 /home/travis/gopath/src/azul3d.org/semver.v2
Cloning into '/home/travis/gopath/src/azul3d.org/semver.v2'...
fatal: unable to access 'https://azul3d.org/semver.v2/': gnutls_handshake() failed: A TLS fatal alert has been received.
package azul3d.org/semver.v2: exit status 128
```

And https://godoc.org/azul3d.org/semver is currently displaying:

![image](https://cloud.githubusercontent.com/assets/1924134/10001929/1e04c6bc-6059-11e5-98ec-9b03302f6cf5.png)

However, when I tried to set an fresh empty GOPATH and `go get -u azul3d.org/semver` locally, it succeeded without problems for me.

**Comment by slimsag** [comment] 2015-09-21 19:19
This is caused by the "flexible"(?) SSL certificate that Cloudflare hands out by default, which some older TLS implementations reject outright. In particular old libopenssl-gnutls versions, such as those on Ubuntu 12.04 / Travis CI.

I'll close this as a duplicate because it will be inherently fixed once azul3d/website#11 is finished (hopefully by/before this weekend).

**Closed by slimsag** 2015-09-21 19:19 UTC

**Comment by shurcooL** [comment] 2015-09-21 20:15
Gotcha, thanks!

**Comment by shurcooL** [comment] 2016-09-17 17:52
FWIW, the godoc part of my original bug report was incorrect. You can see on the screenshot I had the wrong import path, missing ".v2" at the end.

**Comment by slimsag** [comment] 2016-09-17 19:31
I think at one point that package was versioned actually❓probably the time you filed your bug report it was, and then it became unversioned. I'm not sure.

**Comment by shurcooL** [comment] 2016-09-17 19:36
Nah, I suspect it was a typo. The console log output above shows "azul3d.org/semver.v2".

**Comment by slimsag** [comment] 2016-09-17 19:37
Oh I see, you're right.
